version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/' # Location of package manifests
    schedule:
      interval: 'weekly'
      time: '08:00'
      timezone: 'Brazil/East'
    reviewers:
      - '@viniciuslacerda0'
    labels:
      - ':package: dependencies'
    commit-message:
      prefix: 'chore'
      include: 'scope'
